### ISSUE TITLE
Batch update all temlate files

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/installer#2]
Batch update all temlate files:
* readme.md
* readme-zh.md
* .github/ISSUE_TEMPLATE
* .github/workflows
* favicon.ico
* add product folder
* role_appname  need to replace master
* create dev branch
* backup

**Comment by qiaofeng1227** [comment]
## Github自动化构建项目

### 背景
目前网久在github下有两大组织，一共有接近100个项目。外部世界日新月异，公司产品也在不断变化完善。有时候需要对所有产品追加说明文件或者统一修改产品文件的某些地方，人工去一个个修改提交效率极低还容易出错，因此我们希望对github上构建自动化程序，根据规则批量修改所有产品。

### 应用场景
当公司产品发生大批量同一内容追加修改时，在公司镜像服务器执行Github自动化构建脚本来选择要执行的操作，达到批量自动更新的目的。

### 应用范围
根据websoft9和websoft9dev，自动获取需要批量修改的项目名，分别以列表的方式写入两个不同的文件，作为批量修改的对象范围。

### 详细
自动化处理的内容随着发展会不断追加和变更，因此我们这个自动化构建脚本也会不断更新。现阶段而言，我们主要在如下几个方面有自动化构建需求：

- 自动化构建readme文档（中文）
- 自动化构建readme文档（英文）
- 自动化构建issue标准模板
- workflows（目前已有文档自动化构建程序）
- 自动化替换标题栏图标
- 自动化构建产品文件夹
- role项目用main替换master分支
- 所有产品创建dev分支
- backup


### 自动化构建readme文档（中文）
首先建立一个通用的readme模板，差异化地方用变量名称替换。

**Comment by qiaofeng1227** [comment]
have Created new repository for this issue
